name = "CudaNTTs"
uuid = "355ed90f-8f14-42c1-a87f-2eca0abd88af"
authors = ["Alex Pan"]
version = "1.1.1"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
CUDA = "5"
Primes = "0.5"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
